env:
  SEGMENT_BUILDKITE_IMAGE: "buildkite-agent-golang1.23"
  GOPRIVATE: "github.com/segmentio"
  GOFLAGS: "-mod=vendor"
  SEGMENT_CONTEXTS: "aws-credentials,ecr,snyk"
  PATH: "/usr/local/go/bin:${HOME}/go/bin:${HOME}/local/bin:/usr/local/bin:/usr/bin:/bin:$${PATH}"
  GOPATH: "${HOME}/go"
  HOME: "/var/lib/buildkite-agent"
  GOROOT: "/usr/local/go"


steps:
  - label: ":wrench: Install CI dependencies"
    agents:
      queue: v1
    key: install-deps
    commands:
      - mkdir -p deps
      - mkdir -p "${HOME}/local/bin"
      - mkdir -p "${HOME}/go"
      - echo "--- Verifying Go installation"
      - which go || { echo "Go not found, checking installation..."; ls -la /usr/local/go/bin/; }
      - go version || { echo "Go not working, please check installation"; exit 1; }
      - cd deps && ../scripts/pull-deps.sh && cd -
      - echo "--- Installing go tools"
      - GOFLAGS="" go install golang.org/x/tools/cmd/stringer@v0.12.0
      - GOFLAGS="" go install github.com/kevinburke/go-bindata/v4/go-bindata@latest
      - echo "--- Verifying PATH and dependencies"
      - echo "PATH=$PATH"
      - echo "GOPATH=$GOPATH"
      - echo "HOME=$HOME"
      - ls -al "${HOME}/local/bin"
      - echo "--- Verifying required binaries"
      - which -a helm
      - helm version || { echo "Helm not found or not working"; exit 1; }
      - which -a go-bindata
      - go-bindata -version || { echo "go-bindata not found or not working"; exit 1; }
      - which -a stringer || { echo "stringer not found or not working"; exit 1; }

  - label: ":package: Install dependencies"
    agents:
      queue: v1
    key: kubeapply
    depends_on: install-deps
    commands:
      - echo "--- Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - which helm || echo "Helm not found in PATH!"
      - helm version || echo "Helm version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - echo "--- Installing dependencies"
      - make kubeapply

  - label: ":test_tube: Test"
    agents:
      queue: v1
    key: test
    depends_on: kubeapply
    commands:
      - echo "--- Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - which helm || echo "Helm not found in PATH!"
      - helm version || echo "Helm version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - echo "--- Running Tests"
      - |
        make test-ci || {
          echo "Using test-ci target because kind is not supported in CI yet"
          echo "TODO: Get kind tests working in CI"
          exit 1
        }

  - label: ":go: Build"
    agents:
      queue: v1
    key: build
    depends_on: kubeapply
    commands:
      - export PATH="/go/bin:$${HOME}/local/bin:$${PATH}"
      - echo "--- Go Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - make lambda-zip
      - make build-lambda-image

  - group: ":ecr: Publish Lambda"
    if: 'build.branch == "main"'
    steps:
      - label: ":ecr: Publish Lambda Image"
        agents:
          queue: v1
        key: publish-lambda
        depends_on: build
        env:
          SEGMENT_CONTEXTS: "ecr"
        commands:
          - make publish-lambda-image

      - label: ":terraform: Notify for Environment Updates"
        agents:
          queue: v1
        depends_on: publish-lambda
        commands: |
          echo "--- :terraform: New kubeapply-lambda image available"
          echo "Image tag '${VERSION_REF}' has been published to all regions."
          echo ""
          echo "To deploy to staging:"
          echo "1. Update lambda_image_tag in staging Terraform:"
          echo "   terraform workspaces/staging/*/config.tf"
          echo ""
          echo "2. After staging validation, update production:"
          echo "   terraform workspaces/production/*/config.tf"
