env:
  SEGMENT_BUILDKITE_IMAGE: "buildkite-agent-golang1.23"
  GOPRIVATE: "github.com/segmentio"
  GOFLAGS: "-mod=vendor"
  SEGMENT_CONTEXTS: "aws-credentials,ecr,snyk"


steps:
  - label: ":wrench: Install CI dependencies"
    agents:
      queue: v1
    key: install-deps
    commands:
      - export PATH="/go/bin:$${HOME}/local/bin:$${PATH}"
      - mkdir -p deps
      - mkdir -p "${HOME}/local/bin"
      - cd deps && ../scripts/pull-deps.sh && cd -
      - env | grep PATH
      - ls -al "${HOME}/local/bin"
      - which -a helm

  - label: ":package: Install dependencies"
    agents:
      queue: v1
    key: kubeapply
    depends_on: install-deps
    commands:
      - export PATH="/go/bin:$${HOME}/local/bin:$${PATH}"
      - echo "--- Go Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - echo "--- Installing dependencies"
      - make kubeapply

  - label: ":test_tube: Test"
    agents:
      queue: v1
    key: test
    depends_on: kubeapply
    commands:
      - export PATH="/go/bin:$${HOME}/local/bin:$${PATH}"
      - echo "--- Go Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - make test-ci
      - test $? -eq 0 || {
          echo "Using test-ci target because kind is not supported in CI yet"
          echo "TODO: Get kind tests working in CI"
          exit 1
        }

  - label: ":go: Build"
    agents:
      queue: v1
    key: build
    depends_on: kubeapply
    commands:
      - export PATH="/go/bin:$${HOME}/local/bin:$${PATH}"
      - echo "--- Go Environment Check"
      - which go || echo "Go not found in PATH!"
      - go version || echo "Go version check failed!"
      - echo "--- PATH Environment"
      - echo $PATH
      - make lambda-zip
      - make build-lambda-image

  - group: ":ecr: Publish Lambda"
    if: 'build.branch == "main"'
    steps:
      - label: ":ecr: Publish Lambda Image"
        agents:
          queue: v1
        key: publish-lambda
        depends_on: build
        env:
          SEGMENT_CONTEXTS: "ecr"
        commands:
          - make publish-lambda-image

      - label: ":terraform: Notify for Environment Updates"
        agents:
          queue: v1
        depends_on: publish-lambda
        commands: |
          echo "--- :terraform: New kubeapply-lambda image available"
          echo "Image tag '${VERSION_REF}' has been published to all regions."
          echo ""
          echo "To deploy to staging:"
          echo "1. Update lambda_image_tag in staging Terraform:"
          echo "   terraform workspaces/staging/*/config.tf"
          echo ""
          echo "2. After staging validation, update production:"
          echo "   terraform workspaces/production/*/config.tf"
